spring:
  datasource:
    braumat:
      url: @datasource.braumat.url@
      driver-class-name: @datasource.braumat.driver-class-name@
      username: @datasource.braumat.username@
      password: @datasource.braumat.password@
    lims:
      url: @datasource.lims.url@
      driver-class-name: @datasource.lims.driver-class-name@
      username: @datasource.lims.username@
      password: @datasource.lims.password@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  thymeleaf:
    cache: false
 
barcode-query:
  default-uri: @default-uri@

# security
#security:
#  user:
#    name: admin
#    password: admin