spring:
  datasource:
    url: @datasource.url@
    driver-class-name: @datasource.driver-class-name@
  jpa:
    database-platform: @database.platform@
    show-sql: true
    hibernate:
      ddl-auto: create

barcode-query:
  default-uri: @default-uri@

# security
security:
  user:
    name: admin
    password: admin