spring:
  datasource:
    barcode:
      url: @datasource.barcode.url@
      driver-class-name: @datasource.barcode.driver-class-name@
      username: @datasource.barcode.username@
      password: @datasource.barcode.password@
    lims:
      url: @datasource.lims.url@
      driver-class-name: @datasource.lims.driver-class-name@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
 
barcode-query:
  default-uri: @default-uri@

# security
security:
  user:
    name: admin
    password: admin